### ISSUE TITLE
Getting raw data from knxd to this parser

### ISSUE THREAD

**Issue by bohtho** [snowdd1/knx-dpt-parser#1]
I’m having an issue with knxd and my knx-to usb stick (https://github.com/knxd/knxd/issues/322), so am wondering if there’s a way to get raw data out of knxd to parse messages myself with code ?

**Comment by snowdd1** [comment]
Hi bohtho, there is a package called node-eibd  at https://github.com/andreek/node-eibd which I think can be used to pass raw telegrams to the parser, see the PR https://github.com/andreek/node-eibd/pull/48 .
